// src/components/workflow/nodes/_base/before-run-form/form-item.vue
<template>
  <div :class="cn(className)">
    <div v-if="!isBooleanType" class="system-sm-semibold mb-1 flex h-6 items-center gap-1 text-text-secondary">
      <div class="truncate">
        {{ payload.label }}
      </div>
      <span
        v-if="payload.hide === true"
        class="text-xs text-text-tertiary"
      >
        {{ t('workflow.panel.optional_and_hidden') }}
      </span>
      <span
        v-else-if="!payload.required"
        class="text-xs text-text-tertiary"
      >
        {{ t('workflow.panel.optional') }}
      </span>
    </div>
    <div class="grow">
      <el-select
        v-if="type === InputVarType.select"
        v-model="selectValue"
        class="w-full"
        :filterable="false"
        @change="handleSelectChange"
      >
        <el-option
          v-for="option in selectOptions"
          :key="option.value"
          :label="option.name"
          :value="option.value"
        />
      </el-select>

      <el-input
        v-if="type === InputVarType.textInput"
        :model-value="value || ''"
        :placeholder="t('appDebug.variableConfig.inputPlaceholder')"
        :autofocus="autoFocus"
        @update:model-value="handleInputChange"
      />

      <el-input
        v-if="type === InputVarType.number"
        type="number"
        :model-value="value || ''"
        :placeholder="t('appDebug.variableConfig.inputPlaceholder')"
        :autofocus="autoFocus"
        @update:model-value="handleInputChange"
      />

      <el-input
        v-if="type === InputVarType.paragraph"
        type="textarea"
        :model-value="value || ''"
        :placeholder="t('appDebug.variableConfig.inputPlaceholder')"
        :autofocus="autoFocus"
        @update:model-value="handleInputChange"
      />

      <BoolInput
        v-if="isBooleanType"
        :name="payload.label as string"
        :value="!!value"
        :required="payload.required"
        @change="emit('change', $event)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { InputVar } from '@/types'
import { InputVarType } from '@/types'
import cn from '@/utils/classnames'
import BoolInput from './bool-input.vue'

interface Props {
  payload: InputVar
  value: any
  className?: string
  autoFocus?: boolean
  inStepRun?: boolean
}

const emit = defineEmits<{
  change: [value: any]
}>()

const props = withDefaults(defineProps<Props>(), {
  inStepRun: false,
})

const { t } = useI18n()
const { type } = props.payload

const isBooleanType = computed(() => type === InputVarType.checkbox)

const selectValue = computed({
  get: () => props.value || props.payload.default || '',
  set: (val) => emit('change', val),
})

const selectOptions = computed(() =>
  props.payload.options?.map(option => ({ name: option, value: option })) || []
)

const handleSelectChange = (val: any) => {
  emit('change', val)
}

const handleInputChange = (val: string) => {
  emit('change', val)
}
</script>

// src/components/workflow/nodes/_base/before-run-form/form-item.tsx
'use client'
import type { FC } from 'react'
import React, { useCallback, useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import type { InputVar } from '../../../../types'
import { InputVarType } from '../../../../types'
import Select from '@/app/components/base/select'
import Input from '@/app/components/base/input'
import Textarea from '@/app/components/base/textarea'
import TextGenerationImageUploader from '@/app/components/base/image-uploade
import cn from '@/utils/classnames'
import BoolInput from './bool-input'

type Props = {
  payload: InputVar
  value: any
  onChange: (value: any) => void
  className?: string
  autoFocus?: boolean
  inStepRun?: boolean
}

const FormItem: FC<Props> = ({
  payload,
  value,
  onChange,
  className,
  autoFocus,
  inStepRun = false,
}) => {
  const { t } = useTranslation()
  const { type } = payload

  const isBooleanType = type === InputVarType.checkbox

  return (
    <div className={cn(className)}>
      {!isBooleanType && (
        <div className='system-sm-semibold mb-1 flex h-6 items-center gap-1 text-text-secondary'>
          <div className='truncate'>
            { payload.label}
          </div>
          {payload.hide === true ? (
            <span className='system-xs-regular text-text-tertiary'>
              {t('workflow.panel.optional_and_hidden')}
            </span>
          ) : (
            !payload.required && (
              <span className='system-xs-regular text-text-tertiary'>
                {t('workflow.panel.optional')}
              </span>
            )
          )}
        </div>
      )}
      <div className='grow'>
        {
          type === InputVarType.textInput && (
            <Input
              value={value || ''}
              onChange={e => onChange(e.target.value)}
              placeholder={t('appDebug.variableConfig.inputPlaceholder')!}
              autoFocus={autoFocus}
            />
          )
        }

        {
          type === InputVarType.number && (
            <Input
              type="number"
              value={value || ''}
              onChange={e => onChange(e.target.value)}
              placeholder={t('appDebug.variableConfig.inputPlaceholder')!}
              autoFocus={autoFocus}
            />
          )
        }

        {
          type === InputVarType.paragraph && (
            <Textarea
              value={value || ''}
              onChange={e => onChange(e.target.value)}
              placeholder={t('appDebug.variableConfig.inputPlaceholder')!}
              autoFocus={autoFocus}
            />
          )
        }

        {
          type === InputVarType.select && (
            <Select
              className="w-full"
              defaultValue={value || payload.default || ''}
              items={payload.options?.map(option => ({ name: option, value: option })) || []}
              onSelect={i => onChange(i.value)}
              allowSearch={false}
            />
          )
        }

        {isBooleanType && (
          <BoolInput
            name={payload.label as string}
            value={!!value}
            required={payload.required}
            onChange={onChange}
          />
        )}
      </div>
    </div>
  )
}
export default React.memo(FormItem)
